---
# Manages desktop systems
- name: Common Setup Tasks
  hosts: desktops

  tasks:
    - name: Get package facts
      ansible.builtin.package_facts:
        manager: pacman

- import_playbook: ensure_user.yml
- import_playbook: desktops/install_base_packages.yml
- name: Install AUR manually
  ansible.builtin.import_playbook: desktops/setup_aur.yml
  when: "'yay' not in ansible_facts.packages"
- import_playbook: desktops/install_aur_packages.yml
