---
- name: Common Setup Tasks
  hosts: desktops

  tasks:
    - name: Get package facts
      ansible.builtin.package_facts:
        manager: pacman

- import_playbook: ensure_user.yml
- import_playbook: desktops/base_packages.yml
