---
- name: Manage Service States
  hosts: all
  vars:
    services:
      - sddm
      - docker
      - containerd
      - ntpd
      - sshd

  tasks:
    - name: Enable Core Services
      ansible.builtin.systemd_service:
        name: "{{ services }}"
        state: started
        enabled: true
