---
- name: Install AUR packages
  hosts: desktops
  vars_files:
    - package_list.yml

  tasks:
    - name: Install core AUR packages
      become: yes
      become_user: aur_builder
      aur:
        name: "{{ aur_common }}"
        state: present
        use: yay
