---
- name: Setup AUR using YAY
  hosts: desktops
  become: true
  become_user: nobody
  become_method: su

  tasks:
    - name: Clone yay AUR package
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay
        update: yes

    - name: Build and install yay
      ansible.builtin.command:
        chdir: /tmp/yay
        cmd: makepkg -si --noconfirm
        creates: /usr/bin/yay
